### ISSUE TITLE
splitKeyPath undefined

### ISSUE THREAD

**Issue by McPo** [nathanbuchar/electron-settings#37] opened 2016-09-02 13:21 UTC
It appears that there is an issue with one of the libraries used within this project. I submitted a PR regarding this to the upstream project but they don't seem that responsive.

Would you be willing to change the key-path-helper dependency to the git url of my pull request until they merge it in.

https://github.com/atom/key-path-helpers/pull/2

Thanks,
Emmet

(Im surprise no one else is running into this though)

**Comment by nathanbuchar** [comment] 2016-09-02 16:48
Yeah, I don't know if this is an issue with their library, or possibly electron-settings is passing in an undefined value to be split which is causing the error. I'm still trying to track it down

See #33

**Comment by nathanbuchar** [comment] 2016-09-02 17:10
If you could show me your electron-settings debug output, that would be extremely helpful.

Enter this into your terminal `export DEBUG="electron-settings:*"` then start your Electron app (from the same Terminal window).

**Comment by JohnnyCrazy** [comment] 2016-09-05 15:30
@nathanbuchar 
This is definetly an issue with their library, applying @McPo's fix works, but sadly didn't get merged yet. (Already a month old)

Since you can't reproduce this, are you transpiling your `node_modules`? It's very weird because the error pretty much happens in any case when installing this lib.

Would you mind changing your `key-path-helper`-dependency to his PR-Url for the time the PR isn't merged like @McPo suggested? Would prevent everyone rolling out there own fixed versions.

**Comment by nathanbuchar** [comment] 2016-09-05 22:50
@JohnnyCrazy perhaps you're running an older version of Node/Electron that does not support newer syntax. What version of Electron are you running your applications with?

**Comment by JohnnyCrazy** [comment] 2016-09-05 23:42
@nathanbuchar Everything is up-to-date, electron 1.3.5, node 6.5.0.

I just checked with a simple `electron-getting-started`-app, and it seems to work there. My guess, I'm using WebPack to serve the files, and it seems like it's not served the same way electron would (It's sending the JS-Files over the line using a local running web-server). But since it's working with the default setup, guess there is nothing to be changed, sorry for the inconvenience

**Comment by McPo** [comment] 2016-09-06 22:04
It looks like this may be related to transpliing #38 .
Ive added some more notes to that issue as to how to obtain a transpiled version.

**Comment by nathanbuchar** [comment] 2016-09-07 07:28
Closing in lieu of #38

**Closed by nathanbuchar** 2016-09-07 07:28 UTC
Labels: duplicate
